name: publish_tv_app_release

on:
  workflow_dispatch:
  push:
    tags:
      - "tv_*"

jobs:
  build-android:
    uses: ./.github/workflows/build-android.yml
    with:
      app_dir: simple_live_tv_app
      flutter_version: "3.38.5"
      release: true
    secrets:
      keystore_base64: ${{ secrets.TV_KEYSTORE_BASE64 }}
      store_password: ${{ secrets.TV_STORE_PASSWORD }}
      key_password: ${{ secrets.TV_KEY_PASSWORD }}
      key_alias: ${{ secrets.TV_KEY_ALIAS }}
